version: '3.9'

services:
  gitlab-notifications-daemon:
    build:
      dockerfile: Dockerfile
      context: .
      args:        
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - TELEGRAM_USER_CHAT_ID=${TELEGRAM_USER_CHAT_ID}
        - GITLAB_TOKET=${GITLAB_TOKEN}
        - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
        - GITLAB_USERNAME={$GITLAB_USERNAME}
    container_name: ridouchire-gitlab-notifications-daemon
    env_file:
      - '.env'
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_USER_CHAT_ID=${TELEGRAM_USER_CHAT_ID}
      - GITLAB_TOKET=${GITLAB_TOKEN}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - GITLAB_USERNAME=${GITLAB_USERNAME}
